#!/usr/bin/env node

/**
 * sessions.mjs — the real-user sessions of PROJECT_PLAN.md §12.5.
 *
 *   node app/ux/sessions/sessions.mjs cards   # writes task-cards.md from tasks.md
 *   node app/ux/sessions/sessions.mjs score   # reads S*.md, writes results.md
 *
 * `cards` takes each task's goal verbatim from app/ux/tasks.md, so participants
 * get the same words as the simulated testers. `score` reads every session's
 * notes (made from notes-template.md) and computes, per task, the success rate,
 * mean Single Ease Question score and median time, and the System Usability
 * Scale score per participant and overall, against the §12.6 targets.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const TASKS = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9'];
const TARGETS = { success: 0.8, seq: 5.5, sus: 75 };

/** The section of tasks.md from `## <id> ` to the next `## `. */
function section(text, id) {
  const start = text.search(new RegExp(`^## ${id}\\b`, 'm'));
  if (start === -1) throw new Error(`${id} not found in tasks.md`);
  const rest = text.slice(start + 3);
  const end = rest.search(/^## /m);
  return end === -1 ? rest : rest.slice(0, end);
}

/** The blockquote after a marker line, without the `>` prefixes. */
function quoteAfter(text, marker) {
  const lines = text.split(/\r?\n/);
  const at = lines.findIndex((l) => marker.test(l));
  const out = [];
  for (const line of lines.slice(at + 1)) {
    if (/^\s*>/.test(line)) out.push(line.replace(/^\s*> ?/, ''));
    else if (out.length) break;
  }
  return out.join('\n').trim();
}

function cards() {
  const tasks = readFileSync(join(here, '..', 'tasks.md'), 'utf-8');
  const parts = ['# Task cards', '', 'Print one card per page and hand them over one at a time. Read the card aloud too. Generated by `node app/ux/sessions/sessions.mjs cards` from app/ux/tasks.md; do not edit by hand.', ''];
  for (const id of TASKS) {
    const body = section(tasks, id);
    const title = /^(\S+)\s+—\s+(.+)$/m.exec(body)?.[2] ?? id;
    const state = /`(empty|populated|broken)`/.exec(/\*\*Start state:\*\*(.+)/.exec(body)?.[1] ?? '')?.[1] ?? 'populated';
    parts.push(`## ${id} (facilitator: ${title}; start the \`${state}\` sandbox)`, '', quoteAfter(body, /\*\*Goal \(give verbatim\):\*\*/), '', '---', '');
  }
  writeFileSync(join(here, 'task-cards.md'), `${parts.join('\n')}\n`);
  console.log('Wrote app/ux/sessions/task-cards.md');
}

/** One session's notes: the task table and the SUS answers. */
export function parseSession(text) {
  const tasks = {};
  for (const line of text.split(/\r?\n/)) {
    const cells = line.split('|').map((c) => c.trim());
    if (!TASKS.includes(cells[1])) continue;
    const success = cells[2]?.toLowerCase();
    const minutes = Number.parseFloat(cells[3]);
    const seq = Number.parseInt(cells[4], 10);
    if (!['yes', 'partial', 'no'].includes(success)) continue;
    tasks[cells[1]] = { success, minutes: Number.isFinite(minutes) ? minutes : null, seq: seq >= 1 && seq <= 7 ? seq : null };
  }
  const answers = /^SUS:\s*([\d,\s]+)$/m.exec(text)?.[1].split(',').map((n) => Number.parseInt(n, 10)) ?? [];
  return { tasks, sus: answers.length === 10 && answers.every((n) => n >= 1 && n <= 5) ? susScore(answers) : null };
}

/** The standard SUS score: odd items (score − 1), even items (5 − score), sum × 2.5. */
export function susScore(answers) {
  return answers.reduce((sum, a, i) => sum + (i % 2 === 0 ? a - 1 : 5 - a), 0) * 2.5;
}

const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);
const median = (xs) => {
  if (!xs.length) return null;
  const s = [...xs].sort((a, b) => a - b);
  return s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2;
};
const fmt = (n, d = 1) => (n === null ? '—' : n.toFixed(d));

function score() {
  const files = readdirSync(here).filter((f) => /^S\d+.*\.md$/.test(f)).sort();
  const sessions = files.map((f) => ({ file: f, ...parseSession(readFileSync(join(here, f), 'utf-8')) }));
  const lines = ['# Real-user session results', '', `Scored by \`node app/ux/sessions/sessions.mjs score\` from ${files.length} session file(s): ${files.join(', ') || 'none yet'}.`, 'Success counts "yes" as 1 and "partial" as 0 (PROJECT_PLAN.md §12.6 counts completed tasks).', ''];
  lines.push('| Task | Participants | Success | Mean SEQ | Median time (min) | Success ≥ 80% | SEQ ≥ 5.5 |', '|---|---|---|---|---|---|---|');
  let allMet = sessions.length >= 3;
  for (const id of TASKS) {
    const done = sessions.map((s) => s.tasks[id]).filter(Boolean);
    const rate = done.length ? done.filter((t) => t.success === 'yes').length / done.length : null;
    const seq = mean(done.map((t) => t.seq).filter((n) => n !== null));
    const time = median(done.map((t) => t.minutes).filter((n) => n !== null));
    const okRate = rate !== null && rate >= TARGETS.success;
    const okSeq = seq !== null && seq >= TARGETS.seq;
    allMet &&= okRate && okSeq;
    lines.push(`| ${id} | ${done.length} | ${rate === null ? '—' : `${Math.round(rate * 100)}%`} | ${fmt(seq, 2)} | ${fmt(time)} | ${okRate ? 'yes' : 'no'} | ${okSeq ? 'yes' : 'no'} |`);
  }
  const sus = sessions.map((s) => s.sus).filter((n) => n !== null);
  const susMean = mean(sus);
  allMet &&= susMean !== null && susMean >= TARGETS.sus;
  lines.push('', '| Participant | SUS |', '|---|---|', ...sessions.map((s) => `| ${s.file.replace(/\.md$/, '')} | ${fmt(s.sus)} |`), '', `**Mean SUS:** ${fmt(susMean)} (target ≥ ${TARGETS.sus}).`, '');
  lines.push(`**Targets met:** ${allMet ? 'yes' : 'no'}${sessions.length < 3 ? ` (needs at least 3 sessions; ${sessions.length} so far)` : ''}.`, '');
  writeFileSync(join(here, 'results.md'), `${lines.join('\n')}`);
  console.log(lines.join('\n'));
}

const command = process.argv[2];
if (command === 'cards') cards();
else if (command === 'score') score();
else if (command) {
  console.error('Usage: node app/ux/sessions/sessions.mjs cards|score');
  process.exit(2);
}
