import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    // data.js is generated by make-data.mjs from the UX sandbox seed.
    ignores: ['**/node_modules/**', 'ui/dist/**', 'ux/design/prototypes/data.js'],
  },
  js.configs.recommended,
  {
    files: ['**/*.{js,mjs}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.node,
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // The UI is browser code, and until M2 its .jsx files were not linted at all
    // — the block above only matches .js, so every component was unchecked.
    files: ['ui/src/**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^[A-Z]' }],
    },
  },
  {
    // The M7 prototypes' engine is a classic browser script, loaded with a <script> tag.
    files: ['ux/design/prototypes/*.js'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'script',
      globals: globals.browser,
    },
  },
];
